exporter.baseDirectory = .
exporter.use_uuid_filenames = false
exporter.fhir.export = true
exporter.fhir.included_fields = "patient,encounter,condition,observation,procedure,medication,immunization,allergyintolerance,careplans"
exporter.csv.export = false
exporter.json.export = false
exporter.ccda.export = false
exporter.hospital.fhir.export = false
generate.database_type = in_memory
generate.only_alive_patients = false
