"""Entry point for edge analytics application."""

import argparse
import logging
import sys
from pathlib import Path

from src.utils.logger import setup_logger
from src.utils.config import Config


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="MedTech Edge Analytics - Sepsis Detection"
    )
    parser.add_argument(
        "--scenario",
        choices=["healthy", "sepsis", "critical"],
        default="healthy",
        help="Vital scenario to test with",
    )
    parser.add_argument(
        "--model-path",
        default="models/sepsis_model.tflite",
        help="Path to TFLite model",
    )
    parser.add_argument(
        "--loglevel",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        default="INFO",
        help="Logging level",
    )
    
    args = parser.parse_args()
    
    # Setup logging
    logger = setup_logger("medtech.analytics", args.loglevel)
    logger.info("MedTech Edge Analytics - Stage 1")
    logger.info(f"Scenario: {args.scenario}")
    logger.info(f"Model path: {args.model_path}")
    
    # TODO: Implement full inference pipeline
    # This will be generated by Copilot
    logger.info("✅ Initialization complete - waiting for Copilot implementation")


if __name__ == "__main__":
    main()